### ISSUE TITLE
detector dashboard config values

### ISSUE THREAD

**Issue by bormilan** [Kalamansanai/cm-client#146]
I see this at the detector dashboard:
<img width="802" alt="image" src="https://github.com/Kalamansanai/cm-client/assets/71042542/eda594d5-b436-43b8-8c6c-2d58d9179a3c">

char number and coma position are both undifined but, I set them. (couldnt add a detector without set them)

**Comment by balint-szabox** [comment]
@bormilan
I'm unable to reproduce this issue on my end. It's possible that the detector where you observed this bug was added before the feature was implemented that requires both the character number and comma position to be set. Could you please confirm if this might be the case?
